---
- name: "Include OS Family specific Variables."
  include_vars: "{{ ansible_os_family }}.yml"

- name: "Install Prerequisites."
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ nfs_prerequisites }}"
